version: '3.7'
services:
  app:
    container_name: app
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - ./:/app/
    depends_on:
      - db
      - cache
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=${DB_HOST}:${DB_PORT},${REDIS_HOST}:${REDIS_PORT}
      - WAIT_BEFORE_HOSTS=10
      - WAIT_SLEEP_INTERVAL=3
      - TZ=Etc/UTC
    links:
      - db
      - cache

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=Etc/UTC
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    environment:
      - TZ=Etc/UTC

volumes:
  db:
    driver: local
  cache:
    driver: local